export const connectors = [
  {
    id: "ansible",
    name: "Ansible",
    category: "Infrastructure",
    description: "Automate configuration and operational tasks.",
    endpoint: "https://controller.example.com",
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "CI/CD",
    description: "Connect pipelines and build workflows.",
    endpoint: "https://circleci.com",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "Cloud",
    description: "Connect your cloud projects and resources.",
    endpoint: "https://api.digitalocean.com",
  },
  {
    id: "docker",
    name: "Docker Hub",
    category: "Registries",
    description: "Connect container images and repositories.",
    endpoint: "https://hub.docker.com",
  },
  {
    id: "github",
    name: "GitHub",
    category: "CI/CD",
    description: "Connect repositories, actions, and packages.",
    endpoint: "https://api.github.com",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "CI/CD",
    description: "Bring repositories and delivery pipelines together.",
    endpoint: "https://gitlab.com",
  },
  {
    id: "googlecloud",
    name: "Google Cloud",
    category: "Cloud",
    description: "Connect cloud services and projects.",
    endpoint: "https://cloud.google.com",
  },
  {
    id: "harbor",
    name: "Harbor",
    category: "Registries",
    description: "Connect your private container registry.",
    endpoint: "https://harbor.example.com",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    category: "CI/CD",
    description: "Connect builds and automation jobs.",
    endpoint: "https://jenkins.example.com",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "Deployment",
    description: "Connect clusters and application workloads.",
    endpoint: "https://cluster.example.com",
  },
  {
    id: "snyk",
    name: "Snyk",
    category: "Security",
    description: "Connect dependency and application security findings.",
    endpoint: "https://api.snyk.io",
  },
  {
    id: "terraform",
    name: "Terraform Cloud",
    category: "Infrastructure",
    description: "Connect infrastructure workspaces and runs.",
    endpoint: "https://app.terraform.io",
  },
  {
    id: "vault",
    name: "Vault",
    category: "Infrastructure",
    description: "Connect centrally managed secrets.",
    endpoint: "https://vault.example.com",
  },
];
export type Connector = (typeof connectors)[number];
